/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../index";

/**
 * @example
 *     {
 *         userIdentifier: "userIdentifier"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         version: 1.1,
 *         tag: DoptApi.GetFlowRequestTag.Uncommitted,
 *         include: "block"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         version: 1.1,
 *         tag: DoptApi.GetFlowRequestTag.Uncommitted,
 *         include: "block"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         version: 1.1,
 *         tag: DoptApi.GetFlowRequestTag.Uncommitted,
 *         include: "block"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         version: 1.1,
 *         tag: DoptApi.GetFlowRequestTag.Uncommitted,
 *         include: "block"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         version: 1.1,
 *         tag: DoptApi.GetFlowRequestTag.Uncommitted,
 *         include: "block"
 *     }
 */
export interface GetFlowRequest {
    userIdentifier: string;
    groupIdentifier?: string;
    version?: number;
    tag?: DoptApi.GetFlowRequestTag;
    include?: "block";
}
