/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { FlowIntentRequestParamsIntent } from "./FlowIntentRequestParamsIntent";

export const FlowIntentRequestParams: core.serialization.ObjectSchema<
    serializers.FlowIntentRequestParams.Raw,
    DoptApi.FlowIntentRequestParams
> = core.serialization.object({
    sid: core.serialization.string(),
    intent: FlowIntentRequestParamsIntent,
});

export declare namespace FlowIntentRequestParams {
    interface Raw {
        sid: string;
        intent: FlowIntentRequestParamsIntent.Raw;
    }
}
