/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { FlowIntentQueryStringTag } from "./FlowIntentQueryStringTag";

export const FlowIntentQueryString: core.serialization.ObjectSchema<
    serializers.FlowIntentQueryString.Raw,
    DoptApi.FlowIntentQueryString
> = core.serialization.object({
    userIdentifier: core.serialization.string(),
    groupIdentifier: core.serialization.string().optional(),
    version: core.serialization.number().optional(),
    tag: FlowIntentQueryStringTag.optional(),
    force: core.serialization.boolean().optional(),
});

export declare namespace FlowIntentQueryString {
    interface Raw {
        userIdentifier: string;
        groupIdentifier?: string | null;
        version?: number | null;
        tag?: FlowIntentQueryStringTag.Raw | null;
        force?: boolean | null;
    }
}
