/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";

export const GetBlockQueryString: core.serialization.ObjectSchema<
    serializers.GetBlockQueryString.Raw,
    DoptApi.GetBlockQueryString
> = core.serialization.object({
    userIdentifier: core.serialization.string(),
    groupIdentifier: core.serialization.string().optional(),
    version: core.serialization.number(),
});

export declare namespace GetBlockQueryString {
    interface Raw {
        userIdentifier: string;
        groupIdentifier?: string | null;
        version: number;
    }
}
