/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { GetFlowQueryStringTag } from "./GetFlowQueryStringTag";

export const GetFlowQueryString: core.serialization.ObjectSchema<
    serializers.GetFlowQueryString.Raw,
    DoptApi.GetFlowQueryString
> = core.serialization.object({
    userIdentifier: core.serialization.string(),
    groupIdentifier: core.serialization.string().optional(),
    version: core.serialization.number().optional(),
    tag: GetFlowQueryStringTag.optional(),
    include: core.serialization.stringLiteral("block").optional(),
});

export declare namespace GetFlowQueryString {
    interface Raw {
        userIdentifier: string;
        groupIdentifier?: string | null;
        version?: number | null;
        tag?: GetFlowQueryStringTag.Raw | null;
        include?: "block" | null;
    }
}
