/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as DoptApi from "../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization/index";
import * as errors from "../../../../errors/index";

export declare namespace Flows {
    interface Options {
        environment?: core.Supplier<environments.DoptApiEnvironment | string>;
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class Flows {
    constructor(protected readonly _options: Flows.Options) {}

    /**
     * @throws {@link DoptApi.BadRequestError}
     * @throws {@link DoptApi.UnauthorizedError}
     * @throws {@link DoptApi.NotFoundError}
     * @throws {@link DoptApi.InternalServerError}
     *
     * @example
     *     await doptApi.flows.getFlow("sid", {
     *         userIdentifier: "userIdentifier"
     *     })
     *
     * @example
     *     await doptApi.flows.getFlow("string", {
     *         userIdentifier: "string",
     *         groupIdentifier: "string",
     *         version: 1.1,
     *         tag: DoptApi.GetFlowRequestTag.Uncommitted,
     *         include: "block"
     *     })
     */
    public async getFlow(
        sid: string,
        request: DoptApi.GetFlowRequest,
        requestOptions?: Flows.RequestOptions
    ): Promise<DoptApi.GetFlowResponse> {
        const { userIdentifier, groupIdentifier, version, tag, include } = request;
        const _queryParams: Record<string, string | string[] | object | object[]> = {};
        _queryParams["userIdentifier"] = userIdentifier;
        if (groupIdentifier != null) {
            _queryParams["groupIdentifier"] = groupIdentifier;
        }

        if (version != null) {
            _queryParams["version"] = version.toString();
        }

        if (tag != null) {
            _queryParams["tag"] = tag;
        }

        if (include != null) {
            _queryParams["include"] = include;
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.DoptApiEnvironment.Default,
                `v2/flow/${sid}`
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "0.1.1",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
        });
        if (_response.ok) {
            return await serializers.GetFlowResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new DoptApi.BadRequestError(_response.error.body);
                case 401:
                    throw new DoptApi.UnauthorizedError(_response.error.body);
                case 404:
                    throw new DoptApi.NotFoundError(_response.error.body);
                case 500:
                    throw new DoptApi.InternalServerError(_response.error.body);
                default:
                    throw new errors.DoptApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DoptApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DoptApiTimeoutError();
            case "unknown":
                throw new errors.DoptApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * @throws {@link DoptApi.BadRequestError}
     * @throws {@link DoptApi.UnauthorizedError}
     * @throws {@link DoptApi.NotFoundError}
     * @throws {@link DoptApi.InternalServerError}
     *
     * @example
     *     await doptApi.flows.intent("sid", DoptApi.IntentRequestIntent.Finish, {
     *         userIdentifier: "userIdentifier"
     *     })
     *
     * @example
     *     await doptApi.flows.intent("string", DoptApi.IntentRequestIntent.Finish, {
     *         userIdentifier: "string",
     *         groupIdentifier: "string",
     *         version: 1.1,
     *         tag: DoptApi.IntentRequestTag.Uncommitted,
     *         force: true
     *     })
     */
    public async intent(
        sid: string,
        intent: DoptApi.IntentRequestIntent,
        request: DoptApi.IntentRequest,
        requestOptions?: Flows.RequestOptions
    ): Promise<void> {
        const { userIdentifier, groupIdentifier, version, tag, force, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[]> = {};
        _queryParams["userIdentifier"] = userIdentifier;
        if (groupIdentifier != null) {
            _queryParams["groupIdentifier"] = groupIdentifier;
        }

        if (version != null) {
            _queryParams["version"] = version.toString();
        }

        if (tag != null) {
            _queryParams["tag"] = tag;
        }

        if (force != null) {
            _queryParams["force"] = force.toString();
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.DoptApiEnvironment.Default,
                `v2/flow/${sid}/${await serializers.IntentRequestIntent.jsonOrThrow(intent)}`
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "0.1.1",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            body: await serializers.IntentRequest.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new DoptApi.BadRequestError(_response.error.body);
                case 401:
                    throw new DoptApi.UnauthorizedError(_response.error.body);
                case 404:
                    throw new DoptApi.NotFoundError(_response.error.body);
                case 500:
                    throw new DoptApi.InternalServerError(_response.error.body);
                default:
                    throw new errors.DoptApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DoptApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DoptApiTimeoutError();
            case "unknown":
                throw new errors.DoptApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
