/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetFlowResponseState } from "./GetFlowResponseState";
import { GetFlowResponseBlocksItem } from "./GetFlowResponseBlocksItem";

export const GetFlowResponse: core.serialization.ObjectSchema<
    serializers.GetFlowResponse.Raw,
    DoptApi.GetFlowResponse
> = core.serialization.object({
    kind: core.serialization.stringLiteral("flow"),
    type: core.serialization.stringLiteral("flow"),
    uid: core.serialization.string(),
    sid: core.serialization.string(),
    version: core.serialization.number(),
    state: GetFlowResponseState,
    blocks: core.serialization.list(GetFlowResponseBlocksItem).optional(),
});

export declare namespace GetFlowResponse {
    interface Raw {
        kind: "flow";
        type: "flow";
        uid: string;
        sid: string;
        version: number;
        state: GetFlowResponseState.Raw;
        blocks?: GetFlowResponseBlocksItem.Raw[] | null;
    }
}
