/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetFlowResponseBlocksItemState } from "./GetFlowResponseBlocksItemState";
import { GetFlowResponseBlocksItemType } from "./GetFlowResponseBlocksItemType";
import { GetFlowResponseBlocksItemFieldsItem } from "./GetFlowResponseBlocksItemFieldsItem";

export const GetFlowResponseBlocksItem: core.serialization.ObjectSchema<
    serializers.GetFlowResponseBlocksItem.Raw,
    DoptApi.GetFlowResponseBlocksItem
> = core.serialization.object({
    kind: core.serialization.stringLiteral("block"),
    uid: core.serialization.string(),
    sid: core.serialization.string(),
    version: core.serialization.number(),
    state: GetFlowResponseBlocksItemState,
    containerUid: core.serialization.string().optional(),
    transitioned: core.serialization.record(core.serialization.string(), core.serialization.boolean()),
    type: GetFlowResponseBlocksItemType,
    fields: core.serialization.list(GetFlowResponseBlocksItemFieldsItem),
});

export declare namespace GetFlowResponseBlocksItem {
    interface Raw {
        kind: "block";
        uid: string;
        sid: string;
        version: number;
        state: GetFlowResponseBlocksItemState.Raw;
        containerUid?: string | null;
        transitioned: Record<string, boolean>;
        type: GetFlowResponseBlocksItemType.Raw;
        fields: GetFlowResponseBlocksItemFieldsItem.Raw[];
    }
}
