/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetBlockResponseState } from "./GetBlockResponseState";
import { GetBlockResponseType } from "./GetBlockResponseType";
import { GetBlockResponseFieldsItem } from "./GetBlockResponseFieldsItem";

export const GetBlockResponse: core.serialization.ObjectSchema<
    serializers.GetBlockResponse.Raw,
    DoptApi.GetBlockResponse
> = core.serialization.object({
    kind: core.serialization.stringLiteral("block"),
    uid: core.serialization.string(),
    sid: core.serialization.string(),
    version: core.serialization.number(),
    state: GetBlockResponseState,
    containerUid: core.serialization.string().optional(),
    transitioned: core.serialization.record(core.serialization.string(), core.serialization.boolean()),
    type: GetBlockResponseType,
    fields: core.serialization.list(GetBlockResponseFieldsItem),
});

export declare namespace GetBlockResponse {
    interface Raw {
        kind: "block";
        uid: string;
        sid: string;
        version: number;
        state: GetBlockResponseState.Raw;
        containerUid?: string | null;
        transitioned: Record<string, boolean>;
        type: GetBlockResponseType.Raw;
        fields: GetBlockResponseFieldsItem.Raw[];
    }
}
