/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetBlockResponseFieldsItemString } from "./GetBlockResponseFieldsItemString";
import { GetBlockResponseFieldsItemNumber } from "./GetBlockResponseFieldsItemNumber";
import { GetBlockResponseFieldsItemBoolean } from "./GetBlockResponseFieldsItemBoolean";
import { GetBlockResponseFieldsItemRichText } from "./GetBlockResponseFieldsItemRichText";

export const GetBlockResponseFieldsItem: core.serialization.Schema<
    serializers.GetBlockResponseFieldsItem.Raw,
    DoptApi.GetBlockResponseFieldsItem
> = core.serialization
    .union("type", {
        string: GetBlockResponseFieldsItemString,
        number: GetBlockResponseFieldsItemNumber,
        boolean: GetBlockResponseFieldsItemBoolean,
        richText: GetBlockResponseFieldsItemRichText,
    })
    .transform<DoptApi.GetBlockResponseFieldsItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace GetBlockResponseFieldsItem {
    type Raw =
        | GetBlockResponseFieldsItem.String
        | GetBlockResponseFieldsItem.Number
        | GetBlockResponseFieldsItem.Boolean
        | GetBlockResponseFieldsItem.RichText;

    interface String extends GetBlockResponseFieldsItemString.Raw {
        type: "string";
    }

    interface Number extends GetBlockResponseFieldsItemNumber.Raw {
        type: "number";
    }

    interface Boolean extends GetBlockResponseFieldsItemBoolean.Raw {
        type: "boolean";
    }

    interface RichText extends GetBlockResponseFieldsItemRichText.Raw {
        type: "richText";
    }
}
